//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMvcSgq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Acessos
    {
        public long IdAcesso { get; set; }
        public string DsAcesso { get; set; }
        public Nullable<long> IdFuncaoAcesso { get; set; }
    
        public virtual tbl_funcao tbl_funcao { get; set; }
    }
}
