//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMvcSgq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_atividades
    {
        public long IdAtividade { get; set; }
        public Nullable<long> IdAtividadeDiaria { get; set; }
        public Nullable<long> IdEtapa { get; set; }
        public Nullable<int> DsSelecionado { get; set; }
    
        public virtual Tbl_Atividade_Diaria Tbl_Atividade_Diaria { get; set; }
        public virtual tbl_etapa tbl_etapa { get; set; }
    }
}
