//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMvcSgq.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Processo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Processo()
        {
            this.Tbl_Atividade_Diaria = new HashSet<Tbl_Atividade_Diaria>();
            this.tbl_etapa = new HashSet<tbl_etapa>();
        }
    
        public long IdProcesso { get; set; }
        public string Nome { get; set; }
        [Display(Name = "Data Cadastro")]
        public Nullable<System.DateTime> Dt_Cadastro { get; set; }
        [Display(Name = "Data Alteracao")]
        public Nullable<System.DateTime> Dt_Alteracao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Atividade_Diaria> Tbl_Atividade_Diaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_etapa> tbl_etapa { get; set; }
    }
}
