//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMvcSgq.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Atividade_Diaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Atividade_Diaria()
        {
            this.tbl_atividades = new HashSet<tbl_atividades>();
            this.tbl_NaoConformidade = new HashSet<tbl_NaoConformidade>();
        }
    
        public long IdAtividadeDiaria { get; set; }
        public Nullable<long> IdProcesso { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> Dt_Cadastro { get; set; }
        public Nullable<System.DateTime> Dt_Alteracao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_atividades> tbl_atividades { get; set; }
        public virtual tbl_Processo tbl_Processo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_NaoConformidade> tbl_NaoConformidade { get; set; }
    }
}
